#!/bin/zsh

source ~/.cache/wal/colors.sh

dunst &
panel &
picom &
#notify-send "$(fortune)" &
# wmname bspwm

bspc monitor DP-2 -d I II III IV V VI VII
bspc monitor eDP1 -d I II III IV V VI VII
bspc monitor eDP-1 -d I II III IV V VI VII
echo $color1
bspc config focused_border_color "$color1"
bspc config normal_border_color "$color0"
bspc config border_width                    2
bspc config window_gap                      0
bspc config top_padding                     0
bspc config single_monocle                  true
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config pointer_follows_monitor         true
bspc config focus_follows_pointer           false
bspc config click_to_focus                  

# RULES
bspc rule -a discord                        desktop=^7 state=tiled
bspc rule -a '*:Zathura'               		state=tiled
bspc rule -a Zathura               		state=tiled
bspc rule -a '*:surf'                 		state=tiled
bspc rule -a '*:jetbrains-idea' desktop=^6 follow=true
bspc rule -a '*:jetbrains-webstorm' desktop=^6 follow=true
bspc rule -a '*:jetbrains-phpstorm' desktop=^6 follow=true

# Xorg config
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
xsetroot -cursor_name left_ptr
