#!/bin/sh

DIR="$HOME/wallpapers"
WALL=$DIR/$(ls $DIR | dmenu -i -p "Wallpapers: ")
if test -f $WALL; then
	feh --bg-scale $WALL
    # A=$(echo "$(echo "scale=2;$(echo "scale=2;ibase=16; F2" | bc) / 256 * 100" | bc) / 1" | bc)
    # echo $A
    wal -e -t -n -i $WALL --saturate 0.4

    # export ALPHA=${printf '%x\n'$ALPHA}

    makedwm () {
		cd $DWM
		sudo make clean install
		killall dwm
	}
	makest () {
		cd $ST
		# pkill compton
		# compton &
		sudo make clean install
	}
	makedmenu (){
		cd $DMENU
	    sudo make clean install
	}
	makedunst(){
		pkill dunst
		cp $HOME/.cache/wal/dunstrc $HOME/.config/dunst/dunstrc
	}
	
	reloadpolybar(){
		. $HOME/.zprofile
		xrdb $HOME/.cache/wal/colors.Xresources
		panel &
	}
	makedunst
    makest
	makedmenu
	reloadpolybar
	# makedwm
fi
